### ISSUE TITLE
0.6 compile problem on windows (LNK4044 unrecognized option '/ldl')

### ISSUE THREAD

**Issue by theovier** [xushWT/EXPRemake#2]
I tried to compile the 0.6 branch with bam 4.0 on windows and got stuck at 
`[140/141] #1 link teeworlds_d.exe
LINK : warning LNK4044: unrecognized option '/ldl'; ignoring.
bam: error: a build step failed `. 
Using bam's verbose mode I got some overloading erros with the method 'pow' in 

- src/game/server/entities/character.cpp (line 782)
- src/game/server/gamemodes/exp/exp.cpp (line 412)
- src/game/server/player.cpp (line 416)

I asked on the IRC about this and "minus" said that it might be related to a broken build process for windows.

**Comment by GutZuFusss** [comment]
Sorry, no windows support. I am only using linux, and I won't ever install a copy of windows.

You will have to fix this on your own.

**Comment by GutZuFusss** [comment]
But I will point you to where the issue is: Somewhere (idk where anymore, just search) the compilerflags are defined. And if I am not completely wrong "/ldl" should be "-ldl" or just removed entirely.

I hope this helps.

**Comment by theovier** [comment]
Thank you for answering. I just started playing around with the teeworlds compiler and have no clue whatsover where to fix anything but I'll try to find the /ldl part.

Edit: I found `settings.link.flags:Add("-ldl")` in the bam.lua but can't find the "/ldl"

Edit2: When i comment this line `settings.link.flags:Add("-ldl")` out, I don't see the warning anymore but the bam does still fail. Could it be related to the overloading erros? But why do they only appear on windows then?

[error.txt](https://github.com/xushWT/EXPRemake/files/1435529/error.txt)

**Comment by theovier** [comment]
Yes those overloading errors were the problem. I fixed them locally first, gonna upload them later. I dunno why but I had to specifiy the type of the currentweapon. 
So `(int)pow((2, WEAPON_RIFLE)` was transformed into `(int)pow((int)2, (int)WEAPON_RIFLE)`. It does now compile.

#3
